type DefaultChecklistItem = {
  category: string;
  item: string;
  sortOrder: number;
};

const defaultChecklistItems: DefaultChecklistItem[] = [
  // I. Preliminary Information
  { category: 'Preliminary Information', item: 'In the caption, have you correctly identified the jurisdiction in which you will be swearing to the affidavit?', sortOrder: 1 },
  { category: 'Preliminary Information', item: 'Following the caption, does the affidavit begin with the following language: "I, INSERT FULL NAME, RANK, AND OCCUPATION, after being duly sworn, declare as follows":?', sortOrder: 2 },
  { category: 'Preliminary Information', item: 'Have you outlined your training and experience?', sortOrder: 3 },
  { category: 'Preliminary Information', item: 'Have you listed your years of law enforcement experience?', sortOrder: 4 },
  { category: 'Preliminary Information', item: 'Have you listed the number of years you have been with the agency you now work for?', sortOrder: 5 },
  { category: 'Preliminary Information', item: 'Have you identified the number of investigations you have participated in?', sortOrder: 6 },
  { category: 'Preliminary Information', item: 'Have you identified the number of investigations that are similar to the investigation for which you seek this warrant?', sortOrder: 7 },
  { category: 'Preliminary Information', item: 'Have you listed the number of times you have participated in the execution of search warrants?', sortOrder: 8 },
  { category: 'Preliminary Information', item: 'Have you listed the number of times you have participated in similar searches?', sortOrder: 9 },
  { category: 'Preliminary Information', item: 'Have you stated any training, courses, seminars, or schools that you have attended and what you learned there that is relevant to this investigation?', sortOrder: 10 },
  { category: 'Preliminary Information', item: 'Have you stated whether you have qualified as an expert witness and if so, on how many occasions, and in what courts?', sortOrder: 11 },

  // II. Probable Cause
  { category: 'Probable Cause', item: 'Have you indicated the basis of your knowledge?', sortOrder: 1 },
  { category: 'Probable Cause', item: 'Have you described what you personally have observed?', sortOrder: 2 },
  { category: 'Probable Cause', item: 'Have you related your observations to your training and experience to demonstrate their significance (why what you saw was important)?', sortOrder: 3 },
  { category: 'Probable Cause', item: 'Is your affidavit based on information provided by an informant?', sortOrder: 4 },
  { category: 'Probable Cause', item: 'Have you named the informant? If not, have you explained why you have not named the informant?', sortOrder: 5 },
  { category: 'Probable Cause', item: 'Is it a civilian informant?', sortOrder: 6 },
  { category: 'Probable Cause', item: 'Have you stated how the civilian informant came forward with the information?', sortOrder: 7 },
  { category: 'Probable Cause', item: 'Have you demonstrated that the civilian has no motive to lie?', sortOrder: 8 },
  { category: 'Probable Cause', item: 'Have you given the expressed motives of the informant?', sortOrder: 9 },
  { category: 'Probable Cause', item: 'Is the civilian informant an expert, such as a utility company employee?', sortOrder: 10 },
  { category: 'Probable Cause', item: 'Have you identified the employee, and his or her training and experience in the relevant field?', sortOrder: 11 },
  { category: 'Probable Cause', item: 'Have you provided a general information regarding the expert\'s opinion to provide a basis for comparison?', sortOrder: 12 },
  { category: 'Probable Cause', item: 'Is it a criminal informant?', sortOrder: 13 },
  { category: 'Probable Cause', item: 'Have you shown that the informant made declarations against penal (criminal) interest?', sortOrder: 14 },
  { category: 'Probable Cause', item: 'Have you identified any motives for providing the information including: rewards, inducements, plea bargains, payments of money, revenge, hostility, etc.?', sortOrder: 15 },
  { category: 'Probable Cause', item: 'Have you set forth the informant\'s track record?', sortOrder: 16 },
  { category: 'Probable Cause', item: 'Have you described the informant\'s criminal history? (Only disclose details if the informant is not a Confidential Reliable Informant)', sortOrder: 17 },
  { category: 'Probable Cause', item: 'If the informant is a CRI, and has a criminal record, have you simply stated the CRI has a criminal record?', sortOrder: 18 },
  { category: 'Probable Cause', item: 'Is the informant anonymous?', sortOrder: 19 },
  { category: 'Probable Cause', item: 'If the informant is a "911" or "crime stoppers" informant, do you have a copy of the dispatch tape or the officer\'s notes documenting the call?', sortOrder: 20 },
  { category: 'Probable Cause', item: 'Have you provided a reason for crediting the informant\'s information?', sortOrder: 21 },
  { category: 'Probable Cause', item: 'For each informant, have you reproduced that informant\'s statement verbatim or ensured that you have accurately summarized the information he or she provided?', sortOrder: 22 },
  { category: 'Probable Cause', item: 'Have you corroborated the information provided by each informant?', sortOrder: 23 },
  { category: 'Probable Cause', item: 'Have you described police observations and their significance?', sortOrder: 24 },
  { category: 'Probable Cause', item: 'Have you shown how the tips support each other and lead to cross-corroboration?', sortOrder: 25 },
  { category: 'Probable Cause', item: 'Have you related what other law enforcement officers have told you?', sortOrder: 26 },
  { category: 'Probable Cause', item: 'Have you included relevant experience and knowledge of the officers who provided the information?', sortOrder: 27 },
  { category: 'Probable Cause', item: 'Have you provided information you obtained through the search of police records and databases?', sortOrder: 28 },
  { category: 'Probable Cause', item: 'Is the claim of probable cause based on odors, aerial surveillance, etc.?', sortOrder: 29 },
  { category: 'Probable Cause', item: 'Have you described what you saw or smelled?', sortOrder: 30 },
  { category: 'Probable Cause', item: 'Have you explained why you believe it is evidence of a crime?', sortOrder: 31 },
  { category: 'Probable Cause', item: 'Is your claim of probable cause based on a nonhuman source such as field tests, dog sniffs, radar, beeper, etc.?', sortOrder: 32 },
  { category: 'Probable Cause', item: 'Have you described who operated the machine or handled the animal?', sortOrder: 33 },
  { category: 'Probable Cause', item: 'Have you described that person\'s training in using or handling the device or animal?', sortOrder: 34 },
  { category: 'Probable Cause', item: 'Have you described how the mechanical device works and the principles supporting its use?', sortOrder: 35 },
  { category: 'Probable Cause', item: 'Have you stated that the dog was trained to detect narcotics and identified which drugs the dog is trained to detect?', sortOrder: 36 },
  { category: 'Probable Cause', item: 'If the information was obtained from tracking a mechanical beeper ("bird dog"), have you shown either that you obtained a court order or that there was no monitoring while the beeper was in a private residence?', sortOrder: 37 },
  { category: 'Probable Cause', item: 'If you are relying upon odors, have you shown how they would be distinctive? Have you shown how close you were to the source of the odor and why you are able to detect the odor at that distance?', sortOrder: 38 },
  { category: 'Probable Cause', item: 'Is your probable cause based on information obtained in a prior search?', sortOrder: 39 },
  { category: 'Probable Cause', item: 'Have you included the affidavit and the inventory of things seized during the prior search and incorporated these documents by reference?', sortOrder: 40 },
  { category: 'Probable Cause', item: 'Have you mentioned all prior searches of the same premises in this investigation?', sortOrder: 41 },
  { category: 'Probable Cause', item: 'If any of the searches were found unconstitutional, have you provided an independent basis for this search?', sortOrder: 42 },
  { category: 'Probable Cause', item: 'Have you included evidence of the suspect\'s prior arrest and conviction record, as well as the results of any previous searches or investigations involving the same suspect?', sortOrder: 43 },

  // III. Particularity
  { category: 'Particularity', item: 'Have you particularly described the place to be searched?', sortOrder: 1 },
  { category: 'Particularity', item: 'Are you searching a house, building or piece of land?', sortOrder: 2 },
  { category: 'Particularity', item: 'Have you put in the complete address?', sortOrder: 3 },
  { category: 'Particularity', item: 'Have you described the building to be searched?', sortOrder: 4 },
  { category: 'Particularity', item: 'If there is more than one building on the land and you want to search them all, have you shown that the entire premises is under the control of one person or that there is probable cause to search the whole place?', sortOrder: 5 },
  { category: 'Particularity', item: 'Have you included the vehicles on the premises, and have you demonstrated probable cause to support a search of the vehicles?', sortOrder: 6 },
  { category: 'Particularity', item: 'If you want to search people found on the premises, have you established particularized suspicion as to each person, including their personal effects?', sortOrder: 7 },
  { category: 'Particularity', item: 'Are you searching a car or other vehicle?', sortOrder: 8 },
  { category: 'Particularity', item: 'Have you provided the name of the owner or person who is associated with the vehicle?', sortOrder: 9 },
  { category: 'Particularity', item: 'Have you given the license plate number or other identifying information?', sortOrder: 10 },
  { category: 'Particularity', item: 'Have you described the vehicle?', sortOrder: 11 },
  { category: 'Particularity', item: 'Are you searching for a person?', sortOrder: 12 },
  { category: 'Particularity', item: 'If it is possible, have you given the person\'s name?', sortOrder: 13 },
  { category: 'Particularity', item: 'Have you, in all cases, provided a detailed description of the person?', sortOrder: 14 },
  { category: 'Particularity', item: 'Have you described the place at which he or she is to be found?', sortOrder: 15 },
  { category: 'Particularity', item: 'Have you particularly described the items or persons to be seized?', sortOrder: 16 },
  { category: 'Particularity', item: 'Have you established probable cause to believe that each item you want to seize is at the place to be searched?', sortOrder: 17 },
  { category: 'Particularity', item: 'Is the item you want to seize contraband or proceeds of a crime? If so, have you stated the item(s) sought is contraband or proceeds of a crime?', sortOrder: 18 },
  { category: 'Particularity', item: 'Are the items you want to seize "mere evidence of a crime"? If so, have you stated the crime for which the evidence is relevant?', sortOrder: 19 },
  { category: 'Particularity', item: 'If you are relying on generic categories such as "drug records" have you given examples and described the types of items so that officers reading the warrant will know what they are authorized to seize?', sortOrder: 20 },
  { category: 'Particularity', item: 'Have you been as specific as possible given the information available to you at the time you are writing the affidavit?', sortOrder: 21 },
  { category: 'Particularity', item: 'If you will be seizing pagers, computers, or other electronic devices, have you also provided for seizure of the stored information?', sortOrder: 22 },

  // IV. Service of the Warrant
  { category: 'Service of the Warrant', item: 'Are you requesting surreptitious entry? NOTE: For DEA agents, use of a "Sneak and Peak" warrant requires prior approval from DEA Headquarters.', sortOrder: 1 },
  { category: 'Service of the Warrant', item: 'Have you shown a need for such entry?', sortOrder: 2 },
  { category: 'Service of the Warrant', item: 'Does the warrant provide for delayed notice?', sortOrder: 3 },
  { category: 'Service of the Warrant', item: 'Have you consulted with an AUSA? (Note: consultation and consent of an AUSA is absolutely necessary in these cases!)', sortOrder: 4 },
  { category: 'Service of the Warrant', item: 'Are you seeking an anticipatory warrant?', sortOrder: 5 },
  { category: 'Service of the Warrant', item: 'Have you clearly delineated the event that will trigger execution of the warrant? NOTE: The event should be stated in the affidavit and the search warrant itself as a precondition to the execution of the search warrant.', sortOrder: 6 },
  { category: 'Service of the Warrant', item: 'Is this an electronic surveillance request?', sortOrder: 7 },
  { category: 'Service of the Warrant', item: 'Have you met with the AUSA early in the case and followed his or her instructions regarding special procedures and requirements?', sortOrder: 8 },

  // V. Administrative and Procedural Concerns
  { category: 'Administrative and Procedural Concerns', item: 'Have you proofread the affidavit and warrant?', sortOrder: 1 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you spell checked the affidavit and warrant?', sortOrder: 2 },
  { category: 'Administrative and Procedural Concerns', item: 'Are the names of the subjects spelled correctly?', sortOrder: 3 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you named all subjects?', sortOrder: 4 },
  { category: 'Administrative and Procedural Concerns', item: 'Are the dates in the affidavit correct?', sortOrder: 5 },
  { category: 'Administrative and Procedural Concerns', item: 'Does the list of things to search for and seize contain all the items you expect to find?', sortOrder: 6 },
  { category: 'Administrative and Procedural Concerns', item: 'Is the address or license plate number correct?', sortOrder: 7 },
  { category: 'Administrative and Procedural Concerns', item: 'Does the warrant include all the premises, including curtilage, outbuildings, etc., vehicles and persons you want to search?', sortOrder: 8 },
  { category: 'Administrative and Procedural Concerns', item: 'If you have time, have you had somebody else proofread the warrant and affidavit? (They will find things you didn\'t.)', sortOrder: 9 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you verified that the affidavit and warrant attachments are identical?', sortOrder: 10 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you made an appointment to review the affidavit and warrant with an AUSA?', sortOrder: 11 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you made an appointment with the Magistrate to leave a copy of the affidavit and return for a formal application?', sortOrder: 12 },
  { category: 'Administrative and Procedural Concerns', item: 'Have you done your best work in preparing the affidavit?', sortOrder: 13 },
];

export default defaultChecklistItems;
